### ISSUE TITLE
Dancing Dots unexpected messages.

### ISSUE THREAD

**Issue by marocchino** [exercism/elixir-analyzer#381] opened 2023-05-01 04:00 UTC
`Don't forget to annotate all the callback implementations with @impl DancingDots.Animation.`
but I think I'm done annotating.
here is my code. At the time of this writing, I'm in iteration 4.
https://exercism.org/tracks/elixir/exercises/dancing-dots/solutions/marocchino
I'm guessing that one of these two parts is misinterpreted.

```ex
  @impl DancingDots.Animation
  def handle_frame(dot, frame_number, _opts) when rem(frame_number, 4) == 0, do: %{dot | opacity: dot.opacity / 2 }
  def handle_frame(dot, _, _opts), do: dot
# or
  @impl DancingDots.Animation
  def init([velocity: v] = opts) when is_number(v), do: {:ok, opts}
  def init(opts) do
    {:error, "The :velocity option is required, and its value must be a number. Got: #{inspect(opts[:velocity])}"}
  end
```

Since there are several declarations, it would be helpful to have line numbers.

**Comment by angelikatyborska** [comment] 2023-05-01 10:06
Hi, this issue is a duplicate of https://github.com/exercism/elixir-analyzer/issues/381

I'm going to close this issue. Feel free to add any more comments to the other issue.

**Closed by angelikatyborska** 2023-05-01 10:06 UTC
