### ISSUE TITLE
Analysis of File Sniffer

### ISSUE THREAD

**Issue by snowfrogdev** [exercism/elixir-analyzer#304] opened 2022-07-07 14:25 UTC
Here is my solution:
```elixir
defmodule FileSniffer do
  def type_from_extension(extension) do
    case extension do
      "exe" -> "application/octet-stream"
      "bmp" -> "image/bmp"
      "png" -> "image/png"
      "jpg" -> "image/jpg"
      "gif" -> "image/gif"
    end
  end

  def type_from_binary(<<0x7F, 0x45, 0x4C, 0x46, _rest::binary>>), do: "exe" |> type_from_extension
  def type_from_binary(<<0x42, 0x4D, _rest::binary>>), do: "bmp" |> type_from_extension
  def type_from_binary(<<0x89, 0x50, 0x4E, 0x47, _rest::binary>>), do: "png" |> type_from_extension
  def type_from_binary(<<0xFF, 0xD8, 0xFF, _rest::binary>>), do: "jpg" |> type_from_extension
  def type_from_binary(<<0x47, 0x49, 0x46, _rest::binary>>), do: "gif" |> type_from_extension
  
def verify(file_binary, extension) do
    type = extension |> type_from_extension
    if type === file_binary |> type_from_binary do
      {:ok, type}
    else
      {:error, "Warning, file format and file extension do not match."}
    end
  end
end
```

And here is the message I get from the analyzer:

Even though there could be other valid ways to solve this exercise, for the sake of mastering bitstrings please match the first few bytes of the argument of `type_from_binary/1` with the special form `<<>>`.

It seems to me like that is exactly what I'm doing.

**Comment by Lgdev07** [comment] 2022-07-11 22:57
Hey @snowfrogdev 

The problem is with your input on the `png` type.

Your input is 
```elixir
<<0x89, 0x50, 0x4E, 0x47, _rest::binary>>
```

But the analyser expects at least these hexadecimals
```elixir
<<0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A>>
```

You can see the test here:
https://github.com/exercism/elixir-analyzer/blob/706843e21384efc6c2842dc6213d885d9d0ba63b/lib/elixir_analyzer/test_suite/file_sniffer.ex#L33

**Comment by snowfrogdev** [comment] 2022-07-12 13:53
Yeah, I cheated there, for formatting purposes. I figured I didn't need all of it to pass the exercise tests. 😁 So maybe we should modify the exercise tests so that they fail if the entire set of hexadecimals is not used?

**Comment by Lgdev07** [comment] 2022-07-12 19:59
Ah, that makes sense, the problem is in the tests, I will take a look :smile:

**Comment by angelikatyborska** [comment] 2022-09-01 10:14
Resolved in https://github.com/exercism/elixir/pull/1155

**Closed by angelikatyborska** 2022-09-01 10:14 UTC
